### ISSUE TITLE
Separate hash storage for later adding files to archive

### ISSUE THREAD

**Issue by silvioster** [ckolivas/lrzip#10]
Can you please check if it's possible to add this feature to lrzip?
Storing the hashset beside the archive would allow addition of files to the archive without doing an uncompress->untar->tar->compress cycle. For files that differ only slightly, like logs or binary backup snapshots, this would allow using lrzip as the main compression mechanism. 
Possibly might need some kind of file list structure, to be able to extract specific files instead of whole archive contents, although with archives which are uncompressed seldom, like logs/backups, it's less of an issue.
Thanks!

**Comment by ckolivas** [comment]
Pipe dream if I had infinite hours...
