### ISSUE TITLE
Lrztar encryption not working

### ISSUE THREAD

**Issue by tom-doerr** [ckolivas/lrzip#100]
When trying to compress and encrypt a folder with lrztar, I get an error message:

`➜  test     ls -lA
total 4
drwxr-xr-x 2 tom tom 4096 Aug 24 16:15 abc

➜  test      ls -lA abc
total 24
-rw-r--r-- 1 tom tom 11 Aug 24 16:14 test1.txt
-rw-r--r-- 1 tom tom 11 Aug 24 16:11 test.txt

➜  test     lrztar -e abc
/usr/bin/lrztar: illegal option -- e
/usr/bin/lrztar: line 62: ((: v_?=1: syntax error: operand expected (error token is "=1")
Unable to work from STDIN while reading password
Fatal error - exiting
`
I'm currently in the directory test, that's why 'test' is displayed at the beginning of every command. 
I'm using Linux Mint 19 with Kernel 4.15.0-20. 
Could you help me out?

**Comment by ckujau** [comment]
According to [lrztar.1](https://github.com/ckolivas/lrzip/blob/master/man/lrztar.1.pod) the `-e` is not supported. So, that would make this a _feature request_, right? The error message is kinda scary though :)

**Comment by tom-doerr** [comment]
Thanks @ckujau for the reply!
On the man page it says under *Options* to see the `lrzip` man-page, that's why I thought the `-e` opttion from `lrzip` is supported by `lrztar` as well. Am I missing something?

**Comment by ckolivas** [comment]
Unsupported, sorry.
