### ISSUE TITLE
corrupt compressed output when piping or redirecting to stdout

### ISSUE THREAD

**Issue by planet36** [ckolivas/lrzip#102]
When lrzip compresses to a pipe or stdout, sometimes the output is corrupt.

$ lrzip --version
lrzip version 0.631

\# Success case
$ printf '00000000000000000000000000000000000000000000000000000000000000\n' | lrzip -q | lrunzip -q | cat
00000000000000000000000000000000000000000000000000000000000000

\# Fail case
$ printf '000000000000000000000000000000000000000000000000000000000000000\n' | lrzip -q | lrunzip -q | cat
Failed to decompress buffer - lzmaerr=6
Failed to decompress buffer - lzmaerr=6
Failed to decompress in ucompthread
Fatal error - exiting

See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854101

**Comment by jan2000** [comment]
Maybe people should be warned somewhere not to compress with lrzip through a pipe, as this can  result in data loss.

This issue seems to be a longstanding one:
[http://ck-hack.blogspot.com/2012/03/lrzip-0612.html?showComment=1337356929450#c3154145708572533571](http://ck-hack.blogspot.com/2012/03/lrzip-0612.html?showComment=1337356929450#c3154145708572533571)

Furthermore, I found that not only very small files are affected. See the attached file:
```
$ cat data.bin | lrzip -L 1 -q | lrunzip -q | cat
Failed to decompress buffer - lzmaerr=1
Failed to decompress buffer - lzmaerr=1
Failed to decompress in ucompthread
Fatal error - exiting
```
[data.bin.zip](https://github.com/ckolivas/lrzip/files/2605484/data.bin.zip)

**Comment by pete4abw** [comment]
An odd construct. I would break it into pieces and see. I've never seen anyone try to uncompress via pipe. Lrunzip filenane.lrz always works.

On November 21, 2018 11:44:04 AM PST, jan2000 <notifications@github.com> wrote:
>Maybe people should be warned somewhere not to compress with lrzip
>through a pipe, as this can  result in data loss.
>
>This issue seems to be a longstanding one:
>[http://ck-hack.blogspot.com/2012/03/lrzip-0612.html?showComment=1337356929450#c3154145708572533571](http://ck-hack.blogspot.com/2012/03/lrzip-0612.html?showComment=1337356929450#c3154145708572533571)
>
>Furthermore, I found that not only very small files are affected. See
>the attached file:
>```
>$ cat data.bin | lrzip -L 1 -q | lrunzip -q | cat
>Failed to decompress buffer - lzmaerr=1
>Failed to decompress buffer - lzmaerr=1
>Failed to decompress in ucompthread
>Fatal error - exiting
>```
>[data.bin.zip](https://github.com/ckolivas/lrzip/files/2605484/data.bin.zip)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ckolivas/lrzip/issues/102#issuecomment-440787572

-- 
Peter Hyman
+1(609)598-0262
Sent from mobile. Sorry for any typos.

**Comment by jan2000** [comment]
`cat data.bin | lrzip -L 1 -q | lrunzip -q | cat` is only an example. The issue is the same for:
```
$ cat data.bin | lrzip -L 1 -q > data.lrz
$ lrunzip data.lrz
Output filename is: data
Decompressing...
Failed to decompress buffer - lzmaerr=1
Failed to decompress buffer - lzmaerr=1
Failed to decompress in ucompthread
Fatal error - exiting
```

**Comment by pete4abw** [comment]
That won't work. Lrzip filename.lrz. maybe try inserting a - so that lrzip knows pipe is input. Similar to using tar to compress and decompress to another drive. tar -xf -

On November 21, 2018 11:59:21 AM PST, jan2000 <notifications@github.com> wrote:
>`cat data.bin | lrzip -L 1 -q | lrunzip -q | cat` is only an example.
>The issue is the same for:
>```
>$ cat data.bin | lrzip -L 1 -q > data.lrz
>$ lrunzip data.lrz
>Output filename is: data
>Decompressing...
>Failed to decompress buffer - lzmaerr=1
>Failed to decompress buffer - lzmaerr=1
>Failed to decompress in ucompthread
>Fatal error - exiting
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ckolivas/lrzip/issues/102#issuecomment-440791623

-- 
Peter Hyman
+1(609)598-0262
Sent from mobile. Sorry for any typos.

**Comment by jan2000** [comment]
What part does not work? Still, with a dash the issue is still the same:
```
$ cat data.bin | lrzip -L 1 -q - > data.lrz
$ lrunzip data.lrz
Output filename is: data
Decompressing...
Failed to decompress buffer - lzmaerr=1
Failed to decompress buffer - lzmaerr=1
Failed to decompress in ucompthread
Fatal error - exiting
```

**Comment by ckolivas** [comment]
No, there's clearly a bug there during compression, stop trying different ways to avoid it. Finding the time to address it is the biggest issue...

**Comment by tansy** [comment]
Just tested this:

cat lrztar | lrzip -L 1 -q - > lrztar.lrz
cat lrztar.lrz | hexdump

0000000 524c 495a 0600 1467 0000 0000 0000 0000
0000010 0000 0000 0100 0000 0102 1467 0003 0000
0000020 0e00 0300 0000 0000 005f 4a03 4a00 0000
0000030 0000 034c 2201 b200 0001 00c4 2f01 2300
0000040


lrzip lrztar -L 1 -q
cat lrztar.lrz | hexdump

0000000 524c 495a 0600 1467 0000 0000 0000 0000
0000010 005d 0100 0100 0000 0102 1467 0003 0000
0000020 0e00 0300 0000 0000 005f 4a03 4a00 0000
0000030 0000 034c 2201 b200 0001 00c4 2f01 2300
0000040

Differences here are:
0x0010: 00 -> 5D
0x0013: 00 -> 01

According to documentation these are "*16->20  LZMA Properties Encoded (lc,lp,pb,fb, and dictionary size)*", so it should be fairly obvios that during "piped session" they re not set, at all. Maybe that's it or maybe more but I don't have more time to investigate it.

**Comment by tansy** [comment]
Just tested this:

```
cat lrztar | lrzip -L 1 -q - > lrztar.lrz
cat lrztar.lrz | hexdump

0000000 524c 495a 0600 1467 0000 0000 0000 0000
0000010 0000 0000 0100 0000 0102 1467 0003 0000
0000020 0e00 0300 0000 0000 005f 4a03 4a00 0000
0000030 0000 034c 2201 b200 0001 00c4 2f01 2300
0000040
```
And with regular file input:
```
lrzip lrztar -L 1 -q
cat lrztar.lrz | hexdump

0000000 524c 495a 0600 1467 0000 0000 0000 0000
0000010 005d 0100 0100 0000 0102 1467 0003 0000
0000020 0e00 0300 0000 0000 005f 4a03 4a00 0000
0000030 0000 034c 2201 b200 0001 00c4 2f01 2300
0000040
```

Differences here are:
`0x0010: 00 -> 5D`
`0x0013: 00 -> 01`

According to documentation these are "*16->20  LZMA Properties Encoded (lc,lp,pb,fb, and dictionary size)*", so it should be fairly obvios that during "piped session" they re not set, at all. Maybe that's it or maybe more but I don't have more time to investigate it.

**Comment by tansy** [comment]
I tried to debug it and what I found is:
to run it you have to run gdb
$ gdb ./lrzip
and int gdb:
(gdb)$ run -f -o test-pipe.lrz test # for regular file compression
(gdb)$ run < test > test-pipe.lrz # for stdin>stdout compression

What I found was this:

 ./lrzip -f -otest-file.lrz test  |   ./lrzip < test > test-pipe.lrz
----------------------------------|----------------------------------------
static int lzma_compress_buf(...) |static int lzma_compress_buf(...) 
{                                 |{
  @ stream.c:303                  |  @ stream.c:303
  static int lzo_compresses(...)  |  static int lzo_compresses(...)
  {                               |    { 
  ...                             |    ...
  @ stream.c:1877                 |    @ stream.c:1877
  if (!LZO_TEST)                  |    if (!LZO_TEST) // LZO_TEST==1048576
    //--> not                     |      //--> formally not but it jumps:
                                  |    @stream.c:1349
                                  |    			if (!control->magic_written)
                                  |				write_magic(control);
                                  |    // and writes fle header with unset control->lzma_properties
  ret = 1;                        |    // then it comes back to
  }                               |    @stream.c:323
                                  |    lzma_ret = LzmaCompress(...) // sets lzma_properties and continues normally
  @ stream.c:323                  |
  lzma_ret = LzmaCompress(...)    |
    {                             |
    lzma_properties = [0x5d, ...];|
    //are set here;               |
    }                             |
  control->lzma_properties = lzma_properties; |

In addition to that it one runs `$ lrzip -T < test > test.lrz` it's going to be fine.

It looks like multithreading is messing up with this as there is no reason for a program to behave like that in normal flow. I don't know that, so use what I found and patch it, you know better your program than me.

**Comment by tansy** [comment]
I tried to debug it and what I found is:
to run it you have to run gdb
$ gdb ./lrzip
and int gdb:
(gdb)$ run -f -o test-pipe.lrz test # for regular file compression
(gdb)$ run < test > test-pipe.lrz # for stdin>stdout compression

What I found was this:
./lrzip -f -otest-file.lrz test  |   ./lrzip < test > test-pipe.lrz
----------------------------------|----------------------------------------
static int lzma_compress_buf(...) |static int lzma_compress_buf(...) 
{                                 |{
  @ stream.c:303                  |  @ stream.c:303
  static int lzo_compresses(...)  |  static int lzo_compresses(...)
  {                               |    { 
  ...                             |    ...
  @ stream.c:1877                 |    @ stream.c:1877
  if (!LZO_TEST)                  |    if (!LZO_TEST) // LZO_TEST==1048576
    //--> not                     |      //--> formally not but it jumps:
   ...                               |    @stream.c:1349
   ...                               |    			if (!control->magic_written)
   ...                               |				write_magic(control);
   ...                               |    // and writes fle header with unset control->lzma_properties
  ret = 1;                        |    // then it comes back to
  }                               |    @stream.c:323
  ...                                |    lzma_ret = LzmaCompress(...) // sets lzma_properties and continues normally
  @ stream.c:323                  |
  lzma_ret = LzmaCompress(...)    |
    {                             |
    lzma_properties = [0x5d, ...];|
    //are set here;               |
    }                             |
  control->lzma_properties = lzma_properties; |
  
  In addition to that it one runs `$ lrzip -T < test > test.lrz` it's going to be fine.

It looks like multithreading is messing up with this as there is no reason for a program to behave like that in normal flow. I don't know that, so use what I found and patch it, you know better your program than me.

**Comment by tansy** [comment]
I tried to debug it and managed to run it in gdb like that:

```
$ gdb ./lrzip 
(gdb)$ run -f -o test-file.lrz


static int lzma_compress_buf(...) 
{                                 
  @ stream.c:303                  
  static int lzo_compresses(...)  
  {                               
  ...                             
  @ stream.c:1877                 
  if (!LZO_TEST)                  
    //--> not                     
                                  
                                  
                                  
                                  
  ret = 1;                        
  }                               
                                  
  @ stream.c:323
  lzma_ret = LzmaCompress(...) 
    {
    lzma_properties = [0x5d, ...]; //are set here;
    }
  control->lzma_properties = lzma_properties;
```


```
$ gdb ./lrzip 
(gdb)$ run < test > test-pipe.lrz


static int lzma_compress_buf(...) 
{
  @ stream.c:303
  static int lzo_compresses(...)
    { 
    ...
    @ stream.c:1877
    if (!LZO_TEST) // LZO_TEST==1048576
      //--> formally not but it jumps:
    @stream.c:1349
    			if (!control->magic_written)
				write_magic(control);
    // and writes fle header with unset control->lzma_properties
    // then it comes back to
    @stream.c:323
    lzma_ret = LzmaCompress(...) // sets lzma_properties and continues normally

```

  
In addition to that if one runs `$ lrzip -T < test > test.lrz` or `cat test | lrzip -T > test.lrz` for that matter, it's going to be fine.

It looks like multithreading is messing up with this as there is no reason for a program to behave like that in normal flow. I don't know multithreaded programming, so use what I found and utilise it. You know better your program than me.

**Comment by tansy** [comment]
I tried to debug it and managed to run it in gdb like that:

```
$ gdb ./lrzip 
(gdb)$ run -f -o test-file.lrz


static int lzma_compress_buf(...) 
{                                 
  @ stream.c:303                  
  static int lzo_compresses(...)  
  {                               
  ...                             
  @ stream.c:1877                 
  if (!LZO_TEST)                  
    //--> not                     
                          
  ret = 1;                        
  }                               
                                  
  @ stream.c:323
  lzma_ret = LzmaCompress(...) 
    {
    lzma_properties = [0x5d, ...]; //are set here;
    }
  control->lzma_properties = lzma_properties;
```


```
$ gdb ./lrzip 
(gdb)$ run < test > test-pipe.lrz


static int lzma_compress_buf(...) 
{
  @ stream.c:303
  static int lzo_compresses(...)
    { 
    ...
    @ stream.c:1877
    if (!LZO_TEST) // LZO_TEST==1048576
      //--> formally not but it jumps:
    @stream.c:1349
    			if (!control->magic_written)
				write_magic(control);
    // and writes file header with unset control->lzma_properties
    // then it comes back to
    @stream.c:323
    lzma_ret = LzmaCompress(...) // sets lzma_properties and continues normally

```

  
In addition to that if one runs `$ lrzip -T < test > test.lrz` or `cat test | lrzip -T > test.lrz` for that matter, it's going to be fine.

It looks like multithreading is messing up with this as there is no reason for a program to behave like that in normal flow. I don't know multithreaded programming, so use what I found and utilise it. You know better your program than me.

**Comment by ckolivas** [comment]
I think I've tracked down the cause of this and put a fix into git master, thanks.

**Comment by planet36** [comment]
I confirm that my original fail case is now successful with commit 224a630.
