### ISSUE TITLE
Please make it so that lrztar supports the -e flag

### ISSUE THREAD

**Issue by stormdragon2976** [ckolivas/lrzip#103]
Would it be possible to add the support for encryption to the lrztar command? It would be nice to compress a directory and password protect it all at the same time.

**Comment by pete4abw** [comment]
> Would it be possible to add the support for encryption to the lrztar command? It would be nice to compress a directory and password protect it all at the same time.

I took a look at this. the -e option does not work when tar output is piped to lrzip. Even the

`tar --use-compress-program="lrzip options..."`

won't work for the same reason.

However, as a workaround, you can use the tar command directly and then execute lrzip after.  Something like this. The && will run lrzip if tar is successful.

`tar -cf filedir.tar filedir && lrzip -e -n filedir.tar`

**Comment by ckolivas** [comment]
Not realistically possible, sorry.
