### ISSUE TITLE
Corrupt LRZ file

### ISSUE THREAD

**Issue by cyberconsecurity** [ckolivas/lrzip#107]
Looking to seeing you have any ideas on recovering from the following error:
lrzuntar 11.tar.lrz
Not an lrzip file
Fatal error - exiting
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

File was created with lrztar 11, when trying to uncompress it I get the error message above.

**Comment by tansy** [comment]
Did you try to uncompress it? (`$ lrzip -d  11.tar.lrz`)
maybe .lrz file is corrupt?

**Comment by ajz3d** [comment]
I'm experiencing similar problems with several project archives that I had to compress recently with `lrztar`:
```
▶ lrzuntar MASTER.tar.lrz     
Decompressing...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```
Decompression with `lrzip -d` works fine though:
```
▶ lrzip -d MASTER.tar.lrz 
Output filename is: MASTER.tar
Decompressing...
100%     354.42 /    354.42 MB
Average DeCompression Speed: 177.000MB/s
Output filename is: MASTER.tar: [OK] - 371640320 bytes                                
Total time: 00:00:02.77
```
What is interesting, is that if I **compress** offending archives using only one thread (`lrztar -p 1`) then I can unpack them with `lrzuntar` without a problem. Sometimes `-p 1` helps in unpacking too, in case `lrzip -t` or `lrzip -d` segfaults, which I've seen quite frequently.

Using `lrzip` version 0.631

**Comment by ckolivas** [comment]
Quite a lot has changed and there is very little detail in this report. Please open a new issue if it's still a problem on the new release due out shortly.
