### ISSUE TITLE
0.614  warning: ISO C forbids omitting the middle term of a ?: expression 

### ISSUE THREAD

**Issue by jaalto** [ckolivas/lrzip#11]
Hi Con,

Following messages are displayed for the 0.614

      CC       liblrzip.lo
    liblrzip.c: In function 'lrzip_log_cb_set':
    liblrzip.c:601:24: warning: ISO C forbids conversion of function pointer to object pointer type [-peda\
    ntic]
    liblrzip.c:601:22: warning: ISO C forbids assignment between function pointer and 'void *' [-pedantic]
    liblrzip.c: In function 'lrzip_pass_cb_set':
    liblrzip.c:637:25: warning: ISO C forbids conversion of function pointer to object pointer type [-peda\
    ntic]
    liblrzip.c:637:23: warning: ISO C forbids assignment between function pointer and 'void *' [-pedantic]
    liblrzip.c: In function 'lrzip_info_cb_set':
    liblrzip.c:645:25: warning: ISO C forbids conversion of function pointer to object pointer type [-peda\
    ntic]
    liblrzip.c:645:23: warning: ISO C forbids assignment between function pointer and 'void *' [-pedantic]
      CC       lrzip.lo
    lrzip.c: In function 'percentage':
    lrzip.c:873:17: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
      CC       rzip.lo
    rzip.c: In function 'show_distrib':
    rzip.c:555:117: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
    rzip.c: In function 'hash_search':
    rzip.c:643:28: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
    rzip.c:644:35: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
    rzip.c: In function 'rzip_fd':
    rzip.c:1086:55: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
    rzip.c:1164:81: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
      CC       runzip.lo
    runzip.c: In function 'runzip_fd':
    runzip.c:398:121: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
      CC       stream.lo
    stream.c: In function 'lzma_compress_buf':
    stream.c:316:52: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]
      CC       util.lo
    util.c: In function 'setup_overhead':
    util.c:113:52: warning: ISO C forbids omitting the middle term of a ?: expression [-pedantic]

**Comment by ckolivas** [comment]
Fixed in git.
