### ISSUE TITLE
options and config (lrzip.conf)

### ISSUE THREAD

**Issue by tansy** [ckolivas/lrzip#112]
There are few things about options.
1. There is `-c` option that is nonstandard for (de)compressors; in all nix (de)compressors it is writing output to stdout. The way it is in lrzip prevents use of `-I || --use-compress-program` tar option to process archive through compressor of your choice.

2. There is no (command line) option/s for *rzip* or *lzma* compression although these compressors are mentioned in man.

3. Also in *lrzip.conf.5* it's stated that user config file is to be located in `$HOME/./lrzip` which is essentially in `$HOME/lrzip`.
a) I would say it was intended to be `$HOME/.lrzip`.
b) consider moving user *lrzip.conf* to `$HOME/.config` as described in [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables). I know it is not X windows application but many sensible projects think the policy of keeping home directory clean and tidy is a good thing.

**Comment by ckolivas** [comment]
1. When used as 'lrz' instead of 'lrzip' it is in compatibility mode with gzip.
2. Those are subcomponents of lrzip and not meant to be configured directly.
3. Will consider.

**Comment by tansy** [comment]
>> There is no (command line) option/s for rzip or lzma compression although these compressors are mentioned in man.
> Those are subcomponents of lrzip and not meant to be configured directly.
Maybe there is misunderstanding; what I meant was - there are options for gzip (-g), bzip2 (-b) and even for zpaq (-z) but there are not for lzma, rzip. I understand that one of them is default (it can change at some point in life of the program) but still if they are to be used there should be option to choose them.

**Comment by tansy** [comment]
&#3e;&#3e; There is no (command line) option/s for rzip or lzma compression although these compressors are mentioned in man.
&#3e; Those are subcomponents of lrzip and not meant to be configured directly.
Maybe there is misunderstanding; what I meant was - there are options for gzip (-g), bzip2 (-b) and even for zpaq (-z) but there are not for lzma, rzip. I understand that one of them is default (it can change at some point in life of the program) but still if they are to be used there should be option to choose them.

**Comment by ckolivas** [comment]
Rzip is used on _all_ compression _all_ the time in lrzip as the first stage in compression irrespective of configuration choices. Lzma is used by default as the second stage of compression unless disabled by use of -n.

**Comment by tansy** [comment]
&gt;&gt; There is no (command line) option/s for rzip or lzma compression although these compressors are mentioned in man.
&gt; Those are subcomponents of lrzip and not meant to be configured directly.

**Comment by tansy** [comment]
Ok, I understand now. 
Still think that lzma should be able to be chosen explicitly. Its "privileged" status can change if you find something better maybe.

**Comment by ckolivas** [comment]
Will take it under consideration. Unfortunately as you can see this project has been idle for quite some time due to lack of time and interest to address the reports and I can't give any estimate of if and when that will change.

**Comment by pete4abw** [comment]
The error in the lrzip.conf man file is a clear typo. It should be $HOME/.lrzip. The XDG specification comment
In order to prepare a file using rzip ONLY, just use the -n option. It means don't compress, only prepare. It actually is quite useful and fast if you like. Even though LZMA is default method of compression, it can be overridden in the conf file. However, if you specify an alternate compression method in the conf file, and want to override the conf file to choose another compression, use --lzma option or similar.

Options affecting compression:
        **--lzma                  lzma compression (default)** (unless override in lrzip.conf)
        -b, --bzip2             bzip2 compression
        -g, --gzip              gzip compression using zlib
        -l, --lzo               lzo compression (ultra fast)
        **-n, --no-compress       no backend compression - prepare for other compressor**
        -z, --zpaq              zpaq compression (best, extreme compression, extremely slow)

**Comment by tansy** [comment]
I honestly didn't see that option as it is only long. Maybe because not so long time ago I was using standard packet version and there were only short options and manual remained old one, I just replaced executable.

**Comment by pete4abw** [comment]
This forced a review of the code, and it turns out that lrzip will also look for lrzip.conf in the CURRENT directory, as well as /etc/lrzip, $HOME/.lrzip. The first fopen() is for the current dir. I forgot I did that!

> 	/* check for lrzip.conf in ., $HOME/.lrzip and /etc/lrzip */

	char *HOME, homeconf[255];
	char *parametervalue;
	char *parameter;
	char line[255];
	FILE *fp;

	fp = fopen("lrzip.conf", "r");
>

**Comment by pete4abw** [comment]
> Re: b) consider moving user lrzip.conf to $HOME/.config as described in XDG Base Directory Specification. I know it is not X windows application but many sensible projects think the policy of keeping home directory clean and tidy is a good thing.

I thought about this. the `.config` area is not normally written to directly by users. The `lrzip.conf` file is a user created file and not generated or modified by the `lrzip` program. So instructing the user to manually add something to .config could be risky. I do agree that keeping $HOME tidy is worthwhile. And, in fact, `lrzip.conf` is contained in the hidden directory `$HOME/.lrzip` as are many configuration settings for different programs. Node, Java, Git, Openoffice, Vim, Emacs, gimp, mozilla, ssh, subversion, midnight commander, etc. In this sense, `lrzip` behaves very consistently with numerous other applications, both graphical and not.

I'll leave the ultimate decision to Con on this as he is the maintainer. But I think all is fine as is.

**Comment by pete4abw** [comment]
The lrzip.conf issue has been resolved in the latest PR.
