### ISSUE TITLE
Ann: lzma sdk 19.00, other enhancements

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#144]
I've gone ahead and made significant changes to lrzip. Most significant is updating the lzma sdk to version 19.00. Also added x86 filtering which will work with all compression methods. The full changelog is below. **However, to those interested, I would appreciate some testing and feedback**. **NOTE**, I made a change to the magic header which means lrz files made with this version **will not be backward compatible with earlier versions of lrzip**. I also made an important change to the way lrzip buffer sizes are computed. It now favors larger buffers in exchange for fewer threads. The thought being that lzma or other backend compressors will have more data to work with. Other closed issues are dealt with here as well. Please see [lrzip 0.7 with lzma sdk 19.00](https://github.com/pete4abw/lrzip/tree/lzma-sdk-19.00).

> lrzip ChangeLog
>
>DECEMBER 2019, version bump 0.700, Peter Hyman
>
>LZMA SDK 19.00
>
>* Add x86 filter. Add one byte to lzma properties.Magic size unchanged.
>* All new codebase. Include lzma2 code but not used.
>* Multi Threading still handled by p7zip SDK 16.02.
>* Add Dictionary Size capability.
>* Pass absolute dictionary to lzma compressor since lrzip determines size.
>* Pass -1 for threading to lzma encoder so it can choose multi-thread or not.
>* Update lrzip.conf to support dictionary size.
>* Update setup_overhead() in util.c to handle variable dictionary sizes.
>* Update open_stream_out() in stream.c to maximize use of memory and threads.
>* Update info display to show actual lzma settings, lc, lp, pb, and dictionary size.
>* Show ETA for each pass of compression (fixed logic in rzip.c).
>* Display decompression status every 5 seconds instead of multiples of 10%.
>* lrzip can now use nasm or yasm assemblers. AC_CHECK_PROGS in configure.ac.
>* LZMA can now use all levels 1-9. Removed 7/9 scaling from early SDK. LZMA 
default still 5 and will display on summary screen.
>* Update man pages.
>* Some code cleanups (align comments, whitespace removal).

**Comment by pete4abw** [comment]
Update: All filters are now implemented. x86, ARM, ARMT, PPC, SPARC, IA64, and Delta with a delta offset of 1. As previously noted, beca use of the way mmap is implemented, these filters are executed **after** rzip hashing, not before. So their effect may be limited because of prior hashing. man pages, usage screen are updated. Command line options are
`--x86`
`--arm`
`--armt`
`--ppc`
`--sparc`
`--delta` with a potential to select a delta offset (not implemented)

**Comment by ckolivas** [comment]
Given the nature of rzip separation of literals and matches, it would make the most sense to apply lzma filters only to the literals stream.

**Comment by pete4abw** [comment]
> Given the nature of rzip separation of literals and matches, it would make the most sense to apply lzma filters only to the literals stream.

I was hoping to perform the filtering first on an entire chunk, THEN have rzip processing occur. On decompression, reverse the filter after rzip.

The good news is that the filtering will apply to all compression modes, not just lzma.  Anyway, I'm going to sit back and wait for some feedback. Right now, with rzip, the filtering provides minimal benefit. Rzip is pretty good as a filter! :-). Happy New Year!

**Comment by pete4abw** [comment]
> Given the nature of rzip separation of literals and matches, it would make the most sense to apply lzma filters only to the literals stream.

Would that be the Stream 1 blocks?

**Comment by pete4abw** [comment]
Filters applied to stream 1 blocks only. It makes sense, @ckolivas . The Delta filter currently only operates with delta=1 and seems to have good results on uncompressed audio files in particular, WAV, PCM. The various code filters have mixed results. Fortunately, they work really fast.

**Comment by pete4abw** [comment]
## A review of delta filtering
I've experimented a lot lately with filtering. Only the **delta** filter seems to have any signigicant impact (as opposed to x86 and other variants). While many results are unpredictable, because of variability of data, delta seems to work best on files that are uncompressed media and in particular **WAV** files. And filtering data for lrzip's stream 1 has very good results.

File|Delta|Compressed File Size|Pct</br>Compression
---|:---:|:---:|:---:
music.tar|none|513658880|--
music.tar.lrz|none|182655320|64
music.tar.1.lrz|1|176663583|66
music.tar.2.lrz|2|153725774|70
music.tar.3.lrz|3|243602866|53
**music.tar.4.lrz**|**4**|**143857978**|**72**
music.tar.5.lrz|5|255181263|50
music.tar.6.lrz|6|186180345|64
music.tar.7.lrz|7|257076091|50
music.tar.8.lrz|8|158353678|69
...|...|...|...
music.tar.12.lrz|12|166407048|68
music.tar.16.lrz|16|172501290|66
...|...|...|...
music.tar.32.lrz|32|185963388|64
music.tar.64.lrz|64|193343147|62
music.tar.256.lrz|256|200119807|61

It makes sense that even number deltas will outperform odd because of alignment considerations. The issue is being able to predict which delta will work the best. In this test, with 281 tar'ed WAV files, delta=4 worked the best followed by 2, 8, 12, 16, and 1. Other higher deltas were less effective than plain lrzip with no delta.

Anyone who wants to come up with an algorithm for predicting filter effectiveness and selecting the best outcome for compression is welcome to chime in. For most instances, delta=1 works well.

For more information and to test my fork: [lrzip 0.7beta](https://github.com/pete4abw/lrzip/tree/lzma-sdk-19.00)

**Comment by pete4abw** [comment]
ZPAQ 7.15 has been integrated (see #133 ). Filtering on Stream 0 should work with it. Since this fork has diverged significantly from this version - 21 commits ahead, further development and enhancements will be limited to my fork. Should Bugs be encountered on this branch (cf #79 but waiting for testing confirmation) I will review and commit if needed. [See my fork](https://github.com/pete4abw/lrzip/tree/lzma-sdk-19.00)

**Comment by pete4abw** [comment]
I'm pleased to report that ASM Decompression code has been added to [lrzip](https://github.com/pete4abw/lrzip/tree/lzma-sdk-19.00). Thanks to Igor Pavlov, and Conor McCarthy for their help in debugging my efforts in converting the MASM code to NASM. The LZMA ASM Decompressor code yields a 30%+ speed increase in decompression. This code is only for **x86_64** platform and no others.

See [ChangeLog](https://github.com/pete4abw/lrzip/blob/lzma-sdk-19.00/ChangeLog) for a full list of new features in `lrzip 0.715beta`.This code is not compatible with LZMA SDK < 19.00 so cannot be ported to version `0.631` of lrzip.

Here are some benchmarks.

An initial run with `lrzip` yields a significant percentage improvement. Source file: 2,871,971,840 bytes. Compressed file: 1,873,488,679 bytes. YMMV.

Without Assembly
---
Decompressing...
100% 2738.93 / 2738.93 MB
Average DeCompression Speed: **78.229MB/s**
[OK] - 2871971840 bytes
Total time: **00:00:35.57**

With Assembly
---
Decompressing...
100% 2738.93 / 2738.93 MB
Average DeCompression Speed: **130.381MB/s**
[OK] - 2871971840 bytes
Total time: **00:00:21.83**

Percentage improvement: **38% on time**,

**Comment by pete4abw** [comment]
Beginning with release 0.7.27 a new tag and release versioning is in effect. vM.m.c with three dots. This versioning is a change from the past vM.mcc with only two separators. In addition, the micro version will have the count of commits from the last tag/release and the commit number. So, when reporting a bug, a full version will be available with the specific tag. `git describe` with various options is used to fill variables in configure.ac.

```
$ lrzip -V
lrzip version 0.7.27-1-1163458
```
where the `1` indicates the version is 1 commit ahead of the last tag. If the latest HEAD is a tag, the commit count and commit number will be omitted.

Enjoy.

**Comment by pete4abw** [comment]
### [Two new enhancements are now available in my fork](https://github.com/pete4abw/lrzip):
* Threshold testing can now be limited to test for a compression ability of a certain percent.
`-T## | --threshold ##` (1-99) will only permit a chunk whose compressibility is at least 100-##% to be passed to the compressor.
Currently, the system would allow a chunk which was .01% compressible to be passed. This was unreasonable and slowed down compression. This option can also be set in lrzip.conf.
`THRESHOLD = ##` where ## is 1-99.
(Note, in lrzip v 0.7.31 a bug was fixed because the long `--threshold` option had a `required-argument` flag setting. This is a bug in 0.631 too. No processing for threshold was ever done. Now, it is.
The `-T | --threshold` option with no argument will continue to disable Threshold testing altogether.
* RZIP Pre-processing level can now be set independently of compression level.
`-R ## | --rzip-level ##` will set the compression level for the pre-processor buffer from 1-9.
`RZIPLEVEL = ##` in lrzip.conf can also be set.
RZIP uses very little ram, and performs just about as fast at level 9 as level 1. Why not do a more robust pre-process? This means that if you do a level 4 compression, you can set rzip compression to 9 separately.

```
$ lrzip -L1  linux-5.10.tar
Rzip compression: 92.0% 3534010271 / 3840788480
Back end compression: 68.7% 2426118994 / 3534010271
Overall compression: 63.2% 2426118994 / 3840788480
```
```
$ lrzip -L1 -R9 linux-5.10.tar
Rzip compression: 84.2% 3234030447 / 3840788480
Back end compression: 74.1% 2397983078 / 3234030447
Overall compression: 62.4% 2397983078 / 3840788480
```

### Comparison
RZIP Level|Chunk Size|Overall Size|+/-|LRZIP Level|Size
|:---:|---|---|---|:---:|---|
1|3,534,010,271|3,840,788,480|306,778,209|1|2,426,118,994
9|3,234,030,447||606,758,033|1|2,397,983,078

### Discussion
It's not possible to predict whether or if varying RZIP compression levels will have a net positive or negative impact. It will depend on the file type and compression method used. In this example, RZIP performed almost 8% better at level 9 than level 1. RZIP level 9 created a 300MB smaller chunk for the compressor to work with. But the net difference was only 2426118994-2397983078 = **28,135,916** bytes or 0.8%. YMMV, but it's another option for you to consider along with the Threshold Limiting setting.

**Comment by pete4abw** [comment]
@ckolivas  requested to remove post. Closing.
