### ISSUE TITLE
Failed to fstatvfs in compress_file error

### ISSUE THREAD

**Issue by aguedeney** [ckolivas/lrzip#153]
lrzip version 0.631 on Docker Alpine Linux 3.11.6 on Windows 10 Professional. This only occurs with latest Docker using bind mount.

**Comment by pete4abw** [comment]
First time for everything. Never seen this. At this point, lrzip is attempting to get status for the output file. Please run the same lrzip session with the -vv option. Also check for write permissions and free space on the mounted volume you are compressing to.

**Comment by aguedeney** [comment]
lrzip works fine in Docker for Windows using Windows Subsystem for Linux (WSL).  However, when using the default Hyper-V bind mount it fails for some odd reason. It used to work.  PIGZ and PIXZ both work fine with the default Hyper-V bind mount, so I was just wonder what is lrzip doing differently.  I believe in the long run Docker for Windows + WSL is the ultimate solution. Docker for Windows and WSL are brand new. To credit Docker team, they did say the default Hyper-V implementation/installation will not likely work with some CLI applications. If for nothing else, I just wanted to let you all know of this error. Glad to help if you need me to test anything.  As a side note, I was wondering if I could change the "Temporary Directory" to some place else and see if that would work?

$ /usr/bin/lrzip --lzma -vv -f -L 7 "test.tar"
The following options are in effect for this COMPRESSION.
Threading is DISABLED. Number of CPUs detected: 1
Detected 2087997440 bytes ram
Compression level 7
Nice Value: 19
Show Progress
Max Verbose
Overwrite Files
Temporary Directory set as: ./
Compression mode is: LZMA. LZO Compressibility testing enabled
Heuristically Computed Compression Window: 13 = 1300MB
Storage time in seconds 1367884452
Output filename is: test.tar.lrz
File size: 4680192
Failed to fstatvfs in compress_file
Fatal error - exiting

**Comment by aguedeney** [comment]
Turns out the latest stable release of Docker fixes this issue.  I no longer see this error. Strange, however, nothing for lrzip to do here.
