### ISSUE TITLE
Clarification on supported file extension

### ISSUE THREAD

**Issue by ealap** [ckolivas/lrzip#158]
I am using a script with the following lrzip command:

`tar -I "lrzip -q" -cf "${output}.trz" "${source}"`

to be able to control the filename of the output. However, after https://github.com/ckolivas/lrzip/pull/157, it seems the only files supported are files with .tar and .lrz extension. Any input files to lrzip or lrzuntar with another extension would result to an error message:

`lrzip only works on regular FILES`

which to me is a bit vague on what it wants me to do to correctly compress/decompress a file that I had to look into recent commits and see what changed. Anyway, I just preferred .trz over .tar.lrz as a shorthand but it's still okay for me if strict file extension will be enforced, but maybe please update the error message to clearly state this.

I also tried to remove the file extension and it resulted to

`Segmentation fault`

**Comment by ckolivas** [comment]
Reverted the last change, pending a resubmission. Lrzip should be able to compress any filename.
