### ISSUE TITLE
ENHANCEMENT: Allow Multiple Files in lrzip

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#160]
[This is something on my TODO list.](https://github.com/pete4abw/lrzip/issues/7). Instead of lrzip'ing multiple files one by one, why not chain them in one lrz file? All other compression programs permit this. It would eliminate the need for complex bash scripts and lrztar. It would require the elimination of the `-o` or `-O` options for compression and possibly the addition of an `-f` tar-type option for filename (which would mean redefining `-f` force). Instead of making the lrz file the same as the filename being compressed, one would need to define the output file. Comments?

**Comment by pete4abw** [comment]
Of course, `tar -I|--use-compress-program  lrzip -cf file.tar.lrz file1 file2...` works too, although the compression window is reduced due to STDIN

**Comment by ckolivas** [comment]
This is far from trivial and to get the full benefits all the files would need to be compressed concurrently. Adding to an existing archive would require the existing archive to have its index decompressed and then matches added and the index expanded on and completely rewritten. If this is not done and files are just tagged on as separate entities, they won't really benefit from the rzip compression across multiple files at all and will only be as good as compressing each individual file separately and stick the archive together. Try a directly full of files compressed as one big tar file with lrzip, and then lrzip each individual file separately and compare the compression.

**Comment by pete4abw** [comment]
I was thinking something more simplistic and to build on what `lrzip` already does. For example:

`lrzip -r DIR`

will create a bunch of individual **lrz** files, each of which will be zip'ed individually. What I envisioned was a loop for each file found, and append it's magic header to the end of the previous file's stream(s). Basically the same thing as above, but in one **lrz** file. Reading the list of files would mean just following the chain of streams with perhaps an extra offset to the next file or a marker for no more files.

Yes, you would lose the benefit of long range hashing, but using `-r` or multiple files, you lose that anyway with multiple individual lrz files.

Anyway, it's just something I'm considering. For modern systems with lots of ram, `tar -I lrzip` works well enough.
