### ISSUE TITLE
If `which` is unavailable in the $PATH lrztar fails with a confusing error message

### ISSUE THREAD

**Issue by boreq** [ckolivas/lrzip#162]
If `which` is unavailable in the `$PATH` then `lrztar` fails with a confusing error message: 

>lrztar: no tar in your path

This is caused by [this line](https://github.com/ckolivas/lrzip/blob/0906e3d/lrztar#L55) assuming that `which` will always be available. This is not the case in some cases, for example in `archlinux/base` Docker image and caused some confusion before I realized what is going on.

The simplest fix would most likely be to check if which can be executed just before those checks, or just trying to run those programs directly for example by executing `tar --version` and so on.

**Comment by pete4abw** [comment]
Perhaps, just use `tar -I | --use-compress-program= lrzip ...` This works rather well. Also you can embed any options you want or use an `lrzip.conf` file to use various options. `lrztar` has some issues with some options and as a shell file is pretty complex.

**Comment by ckolivas** [comment]
Fixed in git master.
