### ISSUE TITLE
Fixes to Corrupt File errors and segfaults

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#171]
@hfzhang31 @5hadowblad3

I have made fixes to that address Issues #156, #163, #164, #165. All dealt with intentionally corrupted files that resulted in segfaults when lrzip tried to decompress. The fixes will also detect files that are corrupted unintentionally, ;-)

I have modified the `get_fileinfo()` function to serve two purposes.
1. Provide file info as required by `lrzip -i'
2. Provide file validation (which is part of info) without printing output. Just return true or false.

I also made some cleanups to the fatal_  and failure_ class of macros. Some fatal macros were incorrectly used to test conditions, not react to file errors.

The changes can be seen in [My fork](https://github.com/pete4abw/lrzip) which has been bumped to version 0.725. I cannot patch those changes here, but you are welcome to [download the latest release](https://github.com/pete4abw/lrzip/releases). If you wish to keep using 0.631, cherry pick  at your peril the merges because I have added many new features that will break compilation of 0.631 including changes to headers, the control structure, and the magic header feature additions, SDK updates, etc.

**Let me know how this works for you**.

#156 
```
peter@tommyv:/tmp/lrzip$ ./lrzip -dvv test5
The following options are in effect for this DECOMPRESSION.
Threading is ENABLED. Number of CPUs detected: 8
Detected 16562663424 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Temporary Directory set as: ./
Detected lrzip version 0.6 file.
Invalid chunk size 0
Corrupt lrzip archive. Cannot continue
```
#163 
```
peter@tommyv:/tmp/lrzip$ ./lrzip -dvv seg-stream589
The following options are in effect for this DECOMPRESSION.
Threading is ENABLED. Number of CPUs detected: 8
Detected 16562663424 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Temporary Directory set as: ./
Detected lrzip version 0.6 file.
Offset greater than archive size, likely corrupted/truncated archive.
Corrupt lrzip archive. Cannot continue
```
#164 
```
peter@tommyv:/tmp/lrzip$ ./lrzip -dvv seg-stream1523
The following options are in effect for this DECOMPRESSION.
Threading is ENABLED. Number of CPUs detected: 8
Detected 16562663424 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Temporary Directory set as: ./
Detected lrzip version 0.6 file.
Unknown hash, falling back to CRC
Invalid chunk bytes 20
Corrupt lrzip archive. Cannot continue
```
#165 
```
peter@tommyv:/tmp/lrzip$ ./lrzip -dvv uaf-stream546.lrz
The following options are in effect for this DECOMPRESSION.
Threading is ENABLED. Number of CPUs detected: 8
Detected 16562663424 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Temporary Directory set as: ./
Detected lrzip version 0.6 file.
Unknown hash, falling back to CRC
Invalid chunk bytes 20
Corrupt lrzip archive. Cannot continue
```
`lrzip -i` will continue to fail also but may print some output if the file appears normal for a time (i.e. a later stream is corrupt).

```
peter@tommyv:/tmp/lrzip$ ./lrzip -ivv uaf-stream546.lrz
Detected lrzip version 0.6 file.
Unknown hash, falling back to CRC
Rzip chunk 1:
Chunk byte width: 2
Chunk size: 10240
Stream: 0
Offset: 28
Block   Comp    Percent Size
1       none    100.0%  55 / 55 Offset: 0       Head: 0
Stream: 1
Offset: 28
Block   Comp    Percent Size
1       none    2.9%    269 / 9387      Offset: 0       Head: 131
2       lzma    2.7%    24 / 985        Offset: 0       Head: 0
Invalid chunk bytes 20
```

**Comment by ckolivas** [comment]
All fixed in git master.
