### ISSUE TITLE
build broken due to new util/gitdesc.sh script

### ISSUE THREAD

**Issue by SSSSeb** [ckolivas/lrzip#181]
Cloning into 'lrzip'...
 --> 1400a96274d
 STEP 5: RUN cd lrzip ; ./autogen.sh && ./configure --enable-static-bin && make
 Running autoreconf -if...
 ./util/gitdesc.sh: 50: Bad substitution
 ./util/gitdesc.sh: 50: Bad substitution
 /usr/bin/m4:configure.ac:8: bad expression in eval:  + 
 ./util/gitdesc.sh: 50: Bad substitution
 ./util/gitdesc.sh: 50: Bad substitution
 ./util/gitdesc.sh: 50: Bad substitution

**Comment by SSSSeb** [comment]
my platform is ubuntu 20 x86_64

**Comment by SSSSeb** [comment]
root@ea83c26e5999:/lrzip# git diff
diff --git a/util/gitdesc.sh b/util/gitdesc.sh
index 0a34688..062911e 100755
--- a/util/gitdesc.sh
+++ b/util/gitdesc.sh
@@ -1,4 +1,4 @@
-#?bin/sh
+#!/bin/bash
 # Peter Hyman, pete@peterhyman.com
 # December 2020

**Comment by pete4abw** [comment]
My bad. Work dir <> git dir and no check before commit. Sorry.

**Comment by SSSSeb** [comment]
closed by #182
