### ISSUE TITLE
Cannot compile lrzip from github archive

### ISSUE THREAD

**Issue by demhademha** [ckolivas/lrzip#183]
When  downloading the   Tool from the github archives, (not the releases), /utils/getdisc.sh fails:
after running autogen.sh the error is:
Running autoreconf -if...
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
m4:configure.ac:9: bad expression in eval:  + 
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
fatal: not a git repository (or any parent up to mount point /private)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./util/gitdesc.sh: line 56: [: -gt: unary operator expected
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1

A solution to this is to clone the repo, and place the  .git directory in the archive, then run autogen.sh again. It should now work.

**Comment by ckolivas** [comment]
Fixed in git
