### ISSUE TITLE
libtool library versioning incorrect: liblrzip.so.0.0.0

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#186]
While configure.ac defines version_info and release_info, it is not correct. The resulting library has no versioning at all which is important for any program attempting to link against it.
./usr/local/lib:
total 4444
```
-rw-r--r-- 1 peter users 2990152 Feb 16 14:09 liblrzip.a
-rwxr-xr-x 1 peter users     959 Feb 16 14:09 liblrzip.la
lrwxrwxrwx 1 peter users      17 Feb 16 14:09 liblrzip.so -> liblrzip.so.0.0.0
lrwxrwxrwx 1 peter users      17 Feb 16 14:09 liblrzip.so.0 -> liblrzip.so.0.0.0
-rwxr-xr-x 1 peter users 1546320 Feb 16 14:09 liblrzip.so.0.0.0
```
I'm not the libtool expert, but seems to me that liblrzip_la_LDFLAGS is missing `-version-info = $(version_info)`

```
m4_define([lt_rev], m4_eval(v_maj + v_min))
m4_define([lt_cur], v_mic)
m4_define([lt_age], v_min)
```
lt_rev = 6
lt_cur = 31
lt_age = 6

6:31:6 becomes 0.6.31 when the library is built.

```
version_info="lt_rev:lt_cur:lt_age"
release_info="v_rel"
```
version_info is normally **cur:rev:age**, so munging the order does not make sense and is hard to read.
The result is right, however, but I would rename labels.

Try adding `liblrzip_la_LDFLAGS -version-info = $(version_info)`
to Makefile.am

And consider renaming or reordering the lt_ variables in configure.ac

**Comment by ckolivas** [comment]
I'm pretty sure that no project anywhere actually uses the liblrzip library. As nice an idea as it was, given the nature of lrzip, I can understand why it didn't take off, so it's probably a pointless exercise to expend energy on fixing it.

**Comment by pete4abw** [comment]
Well, it's there. So it should be right. 0.0.0 makes no sense. Or just scrap it to a branch and remove from master.

**Comment by ckolivas** [comment]
Yep, there's lots of stuff I'd like to scrap.

**Comment by pete4abw** [comment]
Just closing
