### ISSUE TITLE
lower compression than in previous versions

### ISSUE THREAD

**Issue by Toutatis2** [ckolivas/lrzip#191]
I am using lrzip-0.640 on slackware64-current.
I have a file compressed a some time ago with an older version of lrzip

lrzip -i FreeCAD-0-17.tar.lrz
FreeCAD-0-17.tar.lrz:
lrzip version: 0.6 file
Compression: rzip + lzma
Decompressed file size: 385034240
Compressed file size: 174120138
Compression ratio: 2.211
MD5 used for integrity testing
MD5: 657e693a4007a6b5dafa893118c362d4

I uncompress it, and recompress using lrzip version 0.640:

lrzip FreeCAD-0-17.tar 
Output filename is: FreeCAD-0-17.tar.lrz
FreeCAD-0-17.tar - Compression Ratio: 1.474. Average Compression Speed: 61.167MB/s.
Total time: 00:00:06.40

The compress ratio falls from 2.211 to 1.474

lrzip -i FreeCAD-0-17.tar.lrz
FreeCAD-0-17.tar.lrz:
lrzip version: 0.6 file
Compression: rzip + lzma
Decompressed file size: 385034240
Compressed file size: 261303125
Compression ratio: 1.474
MD5 used for integrity testing
MD5: 657e693a4007a6b5dafa893118c362d4

Now I try with the maximum compression (zpaq):

lrzip -z FreeCAD-0-17.tar
Output filename is: FreeCAD-0-17.tar.lrz
Total: 99%  Chunk: 99%  ZPAQ                                                    7:0% 8:0%                     ZPAQ                                                    7:10%                         ZPAQ                                                    7:20%                         ZPAQ                                                         8:10%                    ZPAQ                                                    7:30%                         ZPAQ                                                    7:40%                         ZPAQ                                                         8:20%                    ZPAQ                                                    7:50%                         ZPAQ                                                    7:60%                         ZPAQ                                                         8:30%                    ZPAQ                                                    7:70%                         ZPAQ                                                    7:80%                         ZPAQ                                                         8:40%                    ZPAQ                                                    7:90%                         ZPAQ                                                         8:50%                    ZPAQ                                                    7:100%                        ZPAQ                                                         8:60%                    ZPAQ                                                         8:70%                    ZPAQ                                                         8:80%                    ZPAQ                                                         8:90%                    ZPAQ                                                         8FreeCAD-0-17.tar - Compression Ratio: 1.477. Average Compression Speed: 28.231MB/s.
Total time: 00:00:12.52

The compression ratio is only a little better

lrzip -i FreeCAD-0-17.tar.lrz
FreeCAD-0-17.tar.lrz:
lrzip version: 0.6 file
Compression: rzip + zpaq
Decompressed file size: 385034240
Compressed file size: 260763791
Compression ratio: 1.477
MD5 used for integrity testing
MD5: 657e693a4007a6b5dafa893118c362d4

**Comment by ckolivas** [comment]
There is already a newer version that addresses this.
