### ISSUE TITLE
Consider enabling MD5 on Mac

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#210]
In a 2011 ChangeLog entry:

> APRIL 2011, version 0.602 Con Kolivas
. . .
> * Disable md5 generation and checking on Apple till it's fixed.

My testing shows that MD5 computes properly now (at least using `libgcrypt`). MD5 should be the default and the #define MD5_RELIABLE should not be checked for. See [lzma-21.03beta](https://github.com/pete4abw/lrzip-next/tree/lzma-21.03beta) branch.

**Comment by ckolivas** [comment]
Enabled.
