### ISSUE TITLE
Error when trying to compress, please help

### ISSUE THREAD

**Issue by NotADinosaur** [ckolivas/lrzip#223]
I apologize for this as I’m rather stupid at command line things (and at linux in general) but I’m trying to compress some game save data as much as possible and I was hoping this could do better than 7zip. The example command at the top of the readme worked, but when I tried to modify it (I didn’t change much at all so I don’t think it would’ve broken it but I guess I did) I get a "failed to stat 2" error after a while and I can’t really find anything on what it means. Could someone help me with fixing this please?

**Comment by pete4abw** [comment]
Skip the README and view the manpage. The TLDR commands are overly complex. Next time show what you did, no one can help you with what you wrote.

**Comment by NotADinosaur** [comment]
Sorry, I don’t really know what I’m doing or what would need to be included.
