### ISSUE TITLE
lrztar doesn't accept -U option

### ISSUE THREAD

**Issue by nemobis** [ckolivas/lrzip#24]
$ lrztar -lDU $dir
Cannot have -U and stdin, unlimited mode disabled.
----
It could fallback to creating a temporary tar file; doing it manually is tedious.

**Comment by ckolivas** [comment]
The warning does not stop it from compressing successfully.

**Comment by kenorb** [comment]
The same problem in here, I'd like to try the Ultimate option.

    $ lrztar -fUz -o my_file.tar.lrz MyDir/

Any workaround?

**Comment by ckolivas** [comment]
Do it in 2 steps? Tar it then lrzip it. lrztar is just a very simple wrapper, not a real archiving tool.
tar cf my_file.tar MyDir/
lrzip -DUz my_file.tar
