### ISSUE TITLE
Successful path through bool lrzip_compress_full may leak

### ISSUE THREAD

**Issue by ariccio** [ckolivas/lrzip#33]
I noticed that the `Lrzip*`, `lr` is freed when `lrzip_run` returns an error, but not when `lrzip_run`, and subsequently `lrzip_compress_full` succeeds.

`lrzip_decompress` also has the same issue. Is this intentional?

I see no other place where that memory is freed, so I highly doubt it is.

(picked up running a `scan-build make`)

**Comment by ckolivas** [comment]
Looks like an oversight, will fix, thanks.
