### ISSUE TITLE
possible call to malloc with argument value 0 in unzip_match

### ISSUE THREAD

**Issue by ariccio** [ckolivas/lrzip#34]
at runzip.c:219 `malloc` is called with a value that is earlier checked to be non-negative, but not nonzero.

I can't rule out a zero-valued len at runzip.c:327, simply because there are too many paths for it to be immediately obvious.

(picked up running a `scan-build make`)

**Comment by ckolivas** [comment]
Checked, not possible unless read_vchars is called with a length of zero which it isn't anywhere in the code. Thanks.
