### ISSUE TITLE
Lrzip should avoid writing large temporary files to tmpfs

### ISSUE THREAD

**Issue by kylemanna** [ckolivas/lrzip#41]
Lrzip runs my system out of memory (sometimes **fatally** depending on what OOM-killer does) if `$TMPDIR` is on a `tmpfs` while decompressing a very large stream with `lrzcat`.  My tmpfs size is half my system memory per the default mount options.

Many distributions set `/tmp` to a `tmpfs` and may also experience this problem when decompressing very large streams.

Setting `$TMPDIR` to a traditional harddrive backed filesystem works fine.

Perhaps lrzip should check before writing temporary files to tmpfs and fail in this case until the user sets a reasonable `$TMPDIR`.

**Comment by kylemanna** [comment]
Related to #31

**Comment by ckolivas** [comment]
It becomes impossible to decompress them by any means then if it is unable to write temporary files at all. There is no workaround for this.
