### ISSUE TITLE
Inaccurage percentage when using zpaq on large files

### ISSUE THREAD

**Issue by john01dav** [ckolivas/lrzip#42]
I use lrzip -z to compress backups (in the form of plain tar archives). It provides great compression, and I'm fine with it taking time to do so. The issue occurs when lrzip displays it's total percentage which quickly goes up, slowly decreasing in speed, before it finally stops at 99% and sits there for sometimes several minutes before finally finishing. I'd like some accurate percentages, in terms of the time remaining in the compression -- perhaps with a command line flag if it takes a significant amount of extra computing power to do.

**Comment by ckolivas** [comment]
The percentage you are seeing is the first pass rzip dictionary compression stage which is correct to stop at 99%. The zpaq compression stage is shown via separate meters accurately in the columns after the first one.
