### ISSUE TITLE
lrzip sticks at total: 3%

### ISSUE THREAD

**Issue by aguythere** [ckolivas/lrzip#45]
Hello. I am currently testing lrzip on a small system backup before moving on to more serious applications. However even this "small" backup is over 100GB (143 to be exact) so lrzip should be a godsend.

Currently I tar the backup (as it contains many full directories) and then compress with lrzip. For a little while it works fine. But once it reaches total: 3% it freezes up; no more progress is made. I don't really know what the problem is....

My most recent test contained no flags at all. I have ~12 GB in physical memory.

**Comment by pete4abw** [comment]
Just curious, why you closed? Sometimes, depending on the composition of the chunk being evaluated, the %compressed may appear to stall. Try using -vv to get some additional output during the compression.

lrzip WILL have trouble with heavily randomized data. E.G.. if you were trying to compress a zip file or compressed drive, or mostly binary info as opposed to a mix of binary and text.

**Comment by aguythere** [comment]
Because I didn't test thoroughly enough. After I made my post I breached the 3% mark on the test with no flags. So obviously it'll simply take a while.
