### ISSUE TITLE
error running lrunzip on large encrypted lrzip file

### ISSUE THREAD

**Issue by GitBillW** [ckolivas/lrzip#48]
My tests suggest that both of these conditions need to apply to produce this error:

- lrzip using the -e (encrypt) flag
- input file big enough to cause lrzip to do more than one pass

Here's a test scenario with an 8GB input file: lrzip, then lrunzip the result.  The output <test8.lrz.out> should be identical to the input <test8>, but it is short:

    lrzip -e -f -v -o test8.lrz test8 && lrunzip -f -v -o test8.lrz.out test8.lrz
    -rw-------  1 root   root 8589934592 2016/04/04 13:26:53 test8
    -rw-------  1 root   root 3100380112 2016/04/04 17:39:10 test8.lrz
    -rw-------  1 root   root 8413675520 2016/04/04 17:46:44 test8.lrz.out

No error messages are seen during lrzip, but "chunk_bytes <#> is invalid in runzip_chunk" is seen during lrunzip.

The same error can be seen with smaller input files if the lrzip -w flag is used to specify a smaller than default compression window size: eg "-w 1" makes the error show up with a 100MB input file.

I'm running on a 64-bit Debian Stable (Jessie) system with 12GB of RAM and an Intel Core i7-950 processor.  I've tried both lrzip-0.616 (the current version on the Debian Stable repo) and lrzip-0.621 which I built myself from the source on https://github.com/ckolivas/lrzip/releases
They both error in the same way. 

Any idea what might be happening, and how I can investigate further?

**Comment by ckolivas** [comment]
That looks like a bad bug indeed. There's probably no need to investigate further unless you're planning on delving into the code as it's almost certainly a bug there. Alas I have no time to address this any time soon.

**Comment by GitBillW** [comment]
I'm in no hurry for a fix, as I'm working around the issue by using lrzip for compression and gpg for encryption.  I recently changed from pxz to lrzip, which gives me better compression while at the same time being kinder to my processor: 8 cores of pxz get the CPU temperature uncomfortably close to the recommended maximum.

When you have the time, a fix would be nice.

**Comment by ckolivas** [comment]
Should be fixed in git now.

**Comment by GitBillW** [comment]
Thanks Con, it's working perfectly now.

--
Bill
