### ISSUE TITLE
lrztar misses support for some lrzip options

### ISSUE THREAD

**Issue by ilario** [ckolivas/lrzip#49]
I'm running lrzip 0.621.

Using lrztar I noticed that -m option (needed to circumvent #44) results in 
`lrztar: illegal option -- m`
The same behavior is caused also by options -e and -i.

Neither options -t and -V works but they prints a different error:
`lrztar: invalid option for lrztar: t`

Thanks

**Comment by ckolivas** [comment]
-m option added to lrztar. -V and -t options do not make sense with lrztar

**Comment by ilario** [comment]
Sorry for not noticing this earlier, but what about `-i` and `-e` options?
