### ISSUE TITLE
lrzip does not work on big endian unless endian.h is present. 

### ISSUE THREAD

**Issue by joelfredrikson** [ckolivas/lrzip#52]
When I was compiling lrzip 0.621 on a Solaris Sparc machine I noticed that lrzip could neither produce correct lrz-files or decompress correct lrz-files.

The problem is in the endian-detection in lrzip_private.h if the system does not have a endian.h-file.
This might look ok, but unless __BIG_ENDIAN and __LITTLE_ENDIAN are already defined to something, the value of __BYTE_ORDER is the same regardless of what WORDS_BIGENDIAN is set to:
#ifndef __BYTE_ORDER
# ifdef WORDS_BIGENDIAN
#  define __BYTE_ORDER __BIG_ENDIAN
# else
#  define __BYTE_ORDER __LITTLE_ENDIAN
# endif
#endif

Which means that further down in lrzip_private.h when you do
  # if __BYTE_ORDER == __LITTLE_ENDIAN
this will return true even when WORDS_BIGENDIAN is set.

I have attached a patch which should fix the problem.

Running attached test with gcc 4.9.3 demonstrates the problem (the test works on Linux x64 also).
% gcc -DWORDS_BIGENDIAN endian_test.c
% ./a.out
Little Endian
 but WORDS_BIGENDIAN is true !!
% gcc -DWORDS_BIGENDIAN -D__BIG_ENDIAN=1 -D__LITTLE_ENDIAN=2 endian_test.c
% ./a.out
Big Endian

[endian_patch.txt](https://github.com/ckolivas/lrzip/files/301323/endian_patch.txt)
[endian_test_c.txt](https://github.com/ckolivas/lrzip/files/301322/endian_test_c.txt)

**Comment by ckolivas** [comment]
Merged, thanks.
