### ISSUE TITLE
does not seem to work on device files

### ISSUE THREAD

**Issue by xerces8** [ckolivas/lrzip#54]
tested with v0.621

`lrzip /dev/sda -o /mnt/backup/sda.compressed`

This creates a 66 byte big file that decompresses to a file with 0 length.

Looks like lrzip reads the size of the device node itself instead of the underlying actual device.

**Comment by ckolivas** [comment]
That's correct. It only works on regular files. The warning I get when using the latest version on devices is the correct: "lrzip only works directly on regular FILES"

**Comment by xerces8** [comment]
Would it be to much work to support device files as input?
Is anything other that regular reads done? (havent (yet) looked at the source)

**Comment by ckolivas** [comment]
Virtually impossible with the current design.
