### ISSUE TITLE
compression level and zpaq

### ISSUE THREAD

**Issue by shrx** [ckolivas/lrzip#56]
The help output suggests that we can choose a compression level with `-L #` switch when using lzma/bzip2/gzip compression.
> Low level options:
>      -L level      set lzma/bzip2/gzip compression level (1-9, default 7)

However, `-L` also affects the compression level when using the ZPAQ compression with `-z`.
ZPAQ's number of compression levels varies with version number [[1](http://mattmahoney.net/dc/zpaq.html)]. What ZPAQ compression levels do the lrzip's compression levels 1-9 correspond to?

**Comment by omegadrh** [comment]
The usage info, manpage, README, etc, should probably be updated to include this information, but here's my understanding of the situation as a starting point.

When ZPAQ compression is used, there are actually only three predefined compression models; method 1 and 2 (the "fast" methods) described on the [zpaq page](http://mattmahoney.net/dc/zpaq.html) apparently aren't available through libzpaq<sup>\[1]</sup>. This leaves us with just methods 3, 4, and 5.

As you noted, the lrzip program requires that the level argument be 1-9; with ZPAQ compression, this gets mapped to libzpaq levels 1-3 in [stream.c:184](https://github.com/ckolivas/lrzip/blob/master/stream.c#L184) as `compression_level / 4 + 1` (obviously rounded to an integer).

What this ultimately means the 1-9 -L options for lrzip map out accordingly:

lrzip -L | libzpaq level | zpaq -method equivalent
---------| ------------- | -----------------------
1 | 1 | 3
2 | 2 | 4
3 | 2 | 4
4 | 2 | 4
5 | 2 | 4
6 | 3 | 5
7 | 3 | 5
8 | 3 | 5
9 | 3 | 5

<br />
\[1]: From libzpaq.h:457 in the [zpaq source code](http://mattmahoney.net/dc/zpaq715.zip)
> It does not work with the fast method type arguments to compress() or compressBlock(). Levels 1, 2, and 3 correspond approximately to "3", "4", and "5".

**Comment by shrx** [comment]
Thanks for your explanation.
