### ISSUE TITLE
Bogus output: No such file or directory

### ISSUE THREAD

**Issue by xerces8** [ckolivas/lrzip#63]
> $ lrzip  -d -o -  -m 10  hda.img.lrz  -f
> Decompressing...
> Unable to malloc buffer of size 693574770 in this environment
> No such file or directory
> Fatal error - exiting

The `No such file or directory` seems wrong. What file is missing? (the specified file exists and is a good lrzip compressed file).

Using version 0.631 on cygwin64.

**Comment by ckolivas** [comment]
Lrzip is heavily OS dependent and only officially supported on a few posix platforms. While many years ago someone contributed some patches for cygwin to compile, no attempt has ever been made to officially test and support cygwin and I would consider it completely broken and unsupported I'm afraid.
