### ISSUE TITLE
no way of non-interactively entering a passprase for -e

### ISSUE THREAD

**Issue by aivanise** [ckolivas/lrzip#72]
I've looked at the source and it seems that there is no way to non-interactively specify a passphrase to the lrzip binary?

Is that really so? I have about 300k files to recompress and would like to encrypt them as well, but don't really feel like entering a passphrase on the terminal 300k times ;)

**Comment by ckolivas** [comment]
Yes that's correct there isn't a mechanism at the moment I'm afraid.

**Comment by ib** [comment]
I'm going to support lrzip in [xarchiver](https://github.com/ib/xarchiver)  which can already handle all types of password protected archives. Without the possibility to add the passphrase after ```-e``` as part of the command line, there will be no encryption support for lrzip and lrzip support will be incomplete!

Would it be possible to implement this?

**Comment by ib** [comment]
> Would it be possible to implement this?

Implementation was pretty easy, a patch has been sent to ckolivas.

**Comment by ib** [comment]
@ckolivas
Any chance you could apply the patches I've sent you?

**Comment by ckolivas** [comment]
Pulled
