### ISSUE TITLE
LRZtar Errror: [Showing this Error]

### ISSUE THREAD

**Issue by mohamed786** [ckolivas/lrzip#76]
H ! there ! as  i have tried to compress a [android source repo] [.repo folder having 48GB of size]
as i have used this command to compress:  **lrztar -z .repo**
```
/usr/bin/lrztar: line 23: 24418 Broken pipe             tar c "$s"
     24419 Killed                  | lrzip ${p[@]// /\\ }
```

Getting this error ! how can i fix this error !

**Comment by Diagonactic** [comment]
I'm seeing the same thing on a 14 GB folder.  Tried to tar it beforehand and just lrzip the same file and received:

```
[1]    25630 killed     lrzip -L 5 Backup.tar
```

**Comment by Diagonactic** [comment]
Almost as soon as I posted this I found the issue.  Ran `dmesg` and noticed this error, which makes a lot of sense given the machine and the other things running on it:

```
[160156.818388] Out of memory: Kill process 25630 (lrzip) score 490 or sacrifice child
[160156.818407] Killed process 25630 (lrzip) total-vm:8630928kB, anon-rss:4980168kB, file-rss:0kB, shmem-rss:0kB
```

So, at least in my case, it was a simple issue of the process running out of memory while executing.
