### ISSUE TITLE
0.608 gcc -Wall -pedantic build warnings

### ISSUE THREAD

**Issue by jaalto** [ckolivas/lrzip#8]
FYI,

Debian now builds with hardened CFLAGS to reveal possible problems. I cranked the flags to maximum "-Wall -pedantic". Perhaps some of the issues could be addresses in later releases.

Flags used were:

LDFLAGS="-Wl,-z,relro -Wl,--as-needed"

CFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -Wall -pedantic"

 ...(this only an exerpt)...

    Types.h:88:14: warning: ISO C90 does not support 'long long' [-Wlong-long]
    Types.h:89:23: warning: ISO C90 does not support 'long long' [-Wlong-long]

    ... warning: C++ style comments are not allowed in ISO C90 [enabled by default]

    LzmaEnc.c:2159:8: warning: variable 'allocaDummy' set but not used [-Wunused-but-set-variable]

    ... warning: ISO C90 does not support the 'll' gnu_printf length modifier [-Wformat]

    lrzip.c:165:55: warning: ISO C99 requires rest arguments to be used [enabled by default]

    main.c:163:2: warning: ISO C does not support the '%Lu' gnu_scanf format [-Wformat]

**Comment by ckolivas** [comment]
Fixed at last in git.

**Comment by ariccio** [comment]
Which commit?

I'm sorry for being pedantic, but I'm curious! :)

**Comment by ckolivas** [comment]
The "fix ISO C warning"s patches.

**Comment by ariccio** [comment]
So, efe3f67, 9756dd3, 90f7228, 2e3eed5, e3598a7 ?
