### ISSUE TITLE
Compression progress and quietness

### ISSUE THREAD

**Issue by ib** [ckolivas/lrzip#80]
Documentation and implementation of option ```-q``` seems wrong.

It says "don't show compression **progress**" but it actually silences much more. With option ```-q``` there is no output at all.

So either ```-q``` should be documented as "quiet" and a new option to only silence the progress displaying the percentages should be added, or current ```-q``` should be changed to ```-qq``` (```--really-quiet``` or so) and only the progress (i.e. percentages) should be suppressed with ```-q```.

**Comment by ckolivas** [comment]
Fixed in latest master.
