### ISSUE TITLE
Quiet mode -q should silence possible free space warning if force mode -f is active

### ISSUE THREAD

**Issue by luksurious** [ckolivas/lrzip#81]
Hello,

I am trying to use `lrzip` in a cron job, and if an error occurs it notifies me.
So any output generated is expected to be an error, which is mailed to an address, as per cron's behavior. Mainly the switch `-q` works fine for this.

However, when the disk where the files are processed has less than the uncompressed files' size available, it will nevertheless generate a warning which cannot be suppressed.
I know for the types of files that the compression is good enough so I will not run out of space, so this warning can be ignored.

```
Warning, possibly inadequate free space detected, but attempting to compress due to -f option being used.
```

Right now, my only option seems to be to completely sent all output of `lrzip` to `/dev/null` or similar so I don't get false alerts.

It would be nice if the switch `-q` or a heavier version `-qq` would also silence this error.

Thanks

**Comment by ckolivas** [comment]
Addressed in d9aea489b94fc1862a30104c2a6b1013826cd5ad
