### ISSUE TITLE
ERROR 12 this should not happen leaving corrupted archive

### ISSUE THREAD

**Issue by g466a** [ckolivas/lrzip#83]
> $ lrzip -v -L 9 /cygdrive/c/tmp_backup/171020-2059_doiServer-backup/171020-2059_doiServer-backup.tar
> The following options are in effect for this COMPRESSION.
> Threading is ENABLED. Number of CPUs detected: 8
> Detected 17080320000 bytes ram
> Compression level 9
> Nice Value: 19
> Show Progress
> Verbose
> Temporary Directory set as: /tmp/
> Compression mode is: LZMA. LZO Compressibility testing enabled
> Heuristically Computed Compression Window: 108 = 10800MB
> Output filename is: /cygdrive/c/tmp_backup/171020-2059_doiServer-backup/171020-2059_doiServer-backup.tar.lrz
> File size: 2273878016
> Will take 1 pass
> Beginning rzip pre-processing phase
> LZMA Multi Thread ERROR: 12. This should not happen.
> Total: 72%  Chunk: 72%
> 
Compression is always interrupted, leaving the archive incomplete. However "ERROR: 12" does not always  appear.

lrzip version 0.631

**Comment by ckolivas** [comment]
Just as a data point, does this happen without the -L 9 option as well?

**Comment by g466a** [comment]
Something else seems to be wrong. Filesystem or Disk problem. I'll check it out and see if I can still reproduce the problem. Didn't see that (or wasn't there?) when I open the ticket...

**Comment by g466a** [comment]
There weren't any filesystem or disk problems, it was just the backup script creating a mess after lrzip failed. The problem can still be reproduced, though the first attempt was successful today (with -L 9). Without the -L 9 it's always successful - if you agree on"always=3 times" ;).

**Comment by ckolivas** [comment]
Unsure if this is still an issue. Please open a new issue with more information if it is.
