### ISSUE TITLE
ucomp_header not documented?

### ISSUE THREAD

**Issue by armijnhemel** [ckolivas/lrzip#97]
I am digging through the format using the description in magic.header.txt but I have this nagging feeling that a data structure has not been described. When running lrzip -tvv on a file I see the following output:

    Reading stream 0 header at 30
    Reading stream 1 header at 40
    Reading ucomp header at 50

but in the documentation I cannot see any explanation about what the "ucomp" header is, or should be and what its purpose is. Looking at the source code I think it is similar to a stream header, but I am not entirely sure. It is also unclear to me where the data blocks should start (after each stream header? At some offset like next block head?). Could you please explain? It would be much appreciated.

**Comment by pete4abw** [comment]
Sorry for the delay. ucomp = uncompressed data. The ucomp header has byte encoded values for the length of Compressed Data, Uncompressed Data, and the offset location of the next header block and compressed data. If is documented in magic.header.txt and the file `stream.c` reads and sets it. The last_head value is 0 for the last chunk.
```
Stream Header Data:
Byte:
0	Compressed data type
(RCD0 bytes)	Compressed data length
(RCD0 bytes)	Uncompressed data length
(RCD0 bytes)	Next block head (0 for last)
```

**Comment by armijnhemel** [comment]
It appears to be not documented. I cannot find a reference to the ucomp header in the text. Perhaps

```
Rzip Chunk Data:
0       Data offsets byte width (meaning length is < (2 * 8)^RCD0)
1       Flag that there is no chunk beyond this
(RCD0 bytes)    Chunk decompressed size (not stored in encrypted file)
XX      Stream 0 header data
XX      Stream 1 header data
```

is missing:

```
XX  Uncompressed header data
```
?
