### ISSUE TITLE
lrztar ignores -D switch

### ISSUE THREAD

**Issue by KhalilSantana** [ckolivas/lrzip#98]
The tittle says it all, when using the -D switch to delete the input file lrztar doesn't actually delete the source file.

man lrzip: 
> -D     If  this  option  is specified then lrzip will delete the source file after successful compression or decompression. When  this  option  is not specified then the source files are not deleted.

[![Demo](https://asciinema.org/a/yvJ3wCtgpxfc5bX5gCMpZ2zt4.png)](https://asciinema.org/a/yvJ3wCtgpxfc5bX5gCMpZ2zt4)

Am I missing something?

**Comment by ckolivas** [comment]
-D is for files whilst lrztar compresses a whole directory. That's quite different semantics and fairly dangerous. It's not clear what the correct behaviour under the circumstances are the safer option is the default.

**Comment by DirtyJukebox** [comment]
Sorry for not answering you back sooner.
I'm not sure the semantics are that different, either way the user signals to lrzip that him/her wants to delete the original file. Deleting folder would simply mean unlinking (deleting) every file inside that folder, then the folder itself. I'm failing to see any danger/unexpected behavior in that.

Another alternative would be adding a --delete-folders flag or something, with an implicit -D.

Either way, is there a list of switches lrztar ignores/behaves differently than lrzip? So this can be better documented (man/info).

**Comment by pete4abw** [comment]
-D only deletes the source file. In the case of lrztar, no source is created as the tar result is piped to lrzip. The idea of using -D to remove a directory and all its contents is a very dangerous idea. An entire system could be wiped. You are correct that more clear documentation and invalid/not-valid option checking in lrztar could be useful.

**Comment by ckolivas** [comment]
Unsafe feature to implement.
